### PR TITLE
Fix crossfade in selection transition

### LINKED ISSUE #865: Background shouldn't show through Webview crossfade
I think currently both webviews use a fade animation. Instead, it should work like this:

1. Current webview is is set to `z-index: 2`. Next webview is set to `z-index: 1; opacity: 1;`
2. Current webview fade animation begins. Because next webview is behind, you get  a clean crossfade.
3. When animation is complete, current webview `z-index: 1`, next webview `z-index: 2`.

### PR DESCRIPTION
**Pull request by gordonbrander**
Fixes #865

### CODE REVIEW

**Comment by gordonbrander** [comment]
Gozala gives it an R+. https://browserhtml.slack.com/archives/general/p1455042029000655

File: src/browser/web-view.js [hunk 1]
```diff
@@ -221,18 +221,6 @@ const SelectAnimationAction = action =>
     }
   );
 
-const UnselectAnimationAction = action =>
-  ( action.type === "End"
-  ? Unselected
```
Comment (Gozala) [inline src/browser/web-view.js]: I just noticed we no longer trigger `Unselected` action which parent component may be expecting (can't remember right now).
