### PR TITLE
Fix the race condition with incorrect loads.

### LINKED ISSUE #618: Loading first site fails
Steps to reproduce:
- get an empty profile.
- launch graphene --start-manifest=...
- the focus is on "Search or enter address..."
- enter a website address, eg mozilla.org, and hit enter.

Expected:
We load the page

Observed:
We load the "File not found. :(" page.

### PR DESCRIPTION
**Pull request by Gozala**
Supposed to fix #618

### CODE REVIEW

**Comment by Gozala** [comment]
Waiting on @fabricedesre to confirm this resolves an issue.

File: src/browser/iframe.js [hunk 1]
```diff
@@ -4,54 +4,50 @@
...
     opener: new VirtualAttribute((node, current) => {
-      const element = current instanceof String &&
-                      current.unbox &&
-                      current.unbox();
-
-      if (element && node !== element) {
-        for (let {name, value} of node.attributes) {
-          element.setAttribute(name, value);
-        }
+      const element = current instanceof String && current.unbox != null ?
```
Comment (gordonbrander) [inline src/browser/iframe.js]: Why check against null here? We need a function.

**Comment by gordonbrander** [comment]
It looks good to me. Let's resolve conflicts and merge.

File: src/browser/iframe.js (hunk 1 above)
Comment (Gozala) [inline src/browser/iframe.js]: I should not have, but also played with http://flowtype.org that's why there all this type annotations. Short story is flow can detect those things and in this case type is `() => any|void` so it will not type check if you don't make sure it's not non `nil` :)
