### PR TITLE
Fix load stop.

### LINKED ISSUE #485: Stop doesn't work (pressing Escape while page is loading)

### PR DESCRIPTION
**Pull request by Gozala**
Fixes #485

### CODE REVIEW

File: src/browser/synthesis-ui.js [hunk 1]
```diff
@@ -138,7 +139,13 @@ define((require, exports, module) => {
     state.mode === 'select-web-view' ? state.set('mode', 'show-web-view') :
     state;
 
+  const escape = state =>
+    state.made === 'show-web-view' ? state :
```
Comment (gordonbrander) [inline src/browser/synthesis-ui.js]: Oops. I missed this. Should be `state.mode`.
